# Matriks dan Sistem Persamaan Linear

## Tujuan Pembelajaran
Memahami dan mampu menerapkan:

1. Metode Penyulihan Maju dan Mundur
2. Metode Eliminasi Gauss
3. Metode Penumpuan Parsial pada Eliminasi Gauss
4. Metode Dekomposisi/Faktorisasi Segitiga
5. Metode Iterasi

untuk mendapatkan solusi dari suatu sistem persamaan linear, serta dapat menentukan determinan dan invers dari suatu matriks.

## Dasar Teori

Bentuk umum dari Sistem Persamaan Linear (SPL) yang terdiri dari $n$ persamaan dengan $n$ variabel bebas adalah:

$$
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + \dots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + \dots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + a_{n3}x_3 + \dots + a_{3n}x_n = b_n \\
$$

SPL tersebut dapat dituliskan dalam bentuk matriks, dengan matriks koefisien dan matriks lengkapnya dituliskan secara berturut-turut sebagai berikut.

$$
\begin{bmatrix}
a_{11} && a_{12} && a_{13} && \dots && a_{1n} && b_1 \\
a_{21} && a_{22} && a_{23} && \dots && a_{2n} && b_2 \\
\vdots && && && && && \vdots\\
a_{n1} && a_{n2} && a_{n3} && \dots && a_{nn} && b_n \\
\end{bmatrix}
$$



Untuk menentukan solusi dari suatu SPL secara analitik, dapat dilakukan dengan metode Operasi Baris Elementer (OBE). OBE dilakukan dengan menyelesaikan matriks lengkap dari SPL dengan cara:
1. Menukarkan dua buah baris
2. Mengalikan suatu baris dengan suatu konstanta tak nol
3. Menambahkan k kali baris ke-i pada baris ke-j.

OBE tidak akan mengubah penyelesaian SPL. Namun, secara analitik OBE hanya dapat dilakukan untuk SPL yang sederhana, yaitu SPL yang memiliki matriks lengkap berukuran relatif kecil. Untuk SPL yang lebih rumit dengan matriks lengkap berukuran relatif besar, diperlukan metode penyelesaian secara numerik.

## Metode Penyelesaian Persamaan Linear

### Metode Penyulihan Maju Mundur
Metode Penyulihan Maju dan Mundur. Suatu SPL yang matriks koefisiennya berbentuk matriks segitiga atas atau bawah dapat diselesaikan dengan metode penyulihan mundur atau maju. Matriks segitiga atas diselesaikan dengan metode penyulihan mundur, sedangkan matriks segitiga bawah diselesaikan dengan metode penyulihan maju.
$$
\begin{bmatrix}
3 && 2 &&   5 &&   7 \\
  && 7 &&  10 &&   2 \\
  &&   && -22 && -24 \\
  &&   &&     &&  45 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{bmatrix}
\begin{bmatrix}
41 \\ 37 \\ -136 \\ 90
\end{bmatrix}
$$

$$
\begin{bmatrix}
 45 &&     &&   &&   \\
-22 && -24 &&   &&   \\
  7 &&  10 && 2 &&   \\
  3 &&   2 && 5 && 7 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{bmatrix}
\begin{bmatrix}
90 \\ -136 \\ 37 \\ 41 \\  
\end{bmatrix}
$$



untuk mendapatkan solusi dari matriks segitiga atas, secara berurutan kita menyelesaikan:

$$
\begin{align}
x_n     & = \frac{1}{a_{n,n}} b_n \\
x_{n-1} & = \frac{1}{a_{n-1, n-1}} (b_{n-1} - a_{n-1, n} x_n) \\
x_{n-2} & = \frac{1}{a_{n-2, n-2}} (b_{n-2} - a_{n-2, n-1}x_{n-1} - a_{n-2, n}x_n) \\
\vdots\\
x_k     & = \frac{1}{a_{k,k}} (b_k - \sum_{i=k+1}^n a_{k,i} x_i) \\
\vdots\\
x_1     & = \frac{1}{a_{1,1}} (b_1 - \sum_{i=2}^n a_{k,i} x_i) \\
\end{align}
$$

metode ini disebut **penyulihan mundur (*back substitution*)** karena kita mencari solusi $x_i$ dari indeks $x_n$ dan secara iteratif 'mundur' ke $x_1$

In [1]:
% Penyulihan Mundur

% Masukan
n = 5;                             % ukuran SPL segitiga atas 
A = triu(randi([-10, 10], n, n+1)) % matriks SPL

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for k=n:-1:1
    if abs(A(k,k)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

% mulai penyulihan
if start_process
    x(n) = A(n, n+1) / A(n, n);
    
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end

x

A =

   -8   -8   -6   -8   -7    9
    0    1    8   -2   -9    2
    0    0   -1   10  -10    0
    0    0    0   -8    8   -1
    0    0    0    0  -10   -3

x =

   1.70000  -4.45000   1.25000   0.42500   0.30000



kita dapat membandingkan solusi dengan bentuk eselon reduksi (*reduced row echelon form*) dari matriks A,

In [2]:
% ingat K = A
K
rref(K)

K =

   -8   -8   -6   -8   -7    9
    0    1    8   -2   -9    2
    0    0   -1   10  -10    0
    0    0    0   -8    8   -1
    0    0    0    0  -10   -3

ans =

   1.00000   0.00000   0.00000   0.00000   0.00000   1.70000
   0.00000   1.00000   0.00000   0.00000   0.00000  -4.45000
   0.00000   0.00000   1.00000   0.00000   0.00000   1.25000
   0.00000   0.00000   0.00000   1.00000   0.00000   0.42500
   0.00000   0.00000   0.00000   0.00000   1.00000   0.30000



### Metode Eliminasi Gauss
Metode ini terdiri dari dua langkah besar, yaitu:
1. Mengubah SPL semula menjadi SPL segitiga atas melalui serangkaian operasi baris elementer (OBE).
2. Menyelesaikan SPL segitiga atas yang terbentuk dengan menggunakan penyulihan mundur.

In [4]:
% Eliminasi Gauss

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n+1)       % matriks ekspansi Ax=b, yakni [A b]

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for i=n:-1:1
    if abs(A(i,i)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

if start_process
    
    % mulai eliminasi
    for k=1:n-1
        for i=(k+1):n
            p = A(i, k)/A(k, k);
            A(i, :) = A(i, :) - p * A(k, :);
        end
        
    end

    % mulai penyulihan
    x(n) = A(n, n+1) / A(n, n);
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end

x

A =

   -5    8   -5   -5   -3   -1
    7   -6    2   -8    1   -6
   -3   10   -5    6   -8   -9
    2    4   -3  -10   -3   -9
   -9    2   -1   -6   -8   -9

x =

  -0.83652  -0.64172  -1.44268   0.36518   1.81210



In [5]:
rref(K)

ans =

   1.00000   0.00000   0.00000   0.00000   0.00000  -0.83652
   0.00000   1.00000   0.00000   0.00000   0.00000  -0.64172
   0.00000   0.00000   1.00000   0.00000   0.00000  -1.44268
   0.00000   0.00000   0.00000   1.00000   0.00000   0.36518
   0.00000   0.00000   0.00000   0.00000   1.00000   1.81210



### Metode Penumpuan Parsial pada Eliminasi Gauss
Teknik penumpuan parsial dilakukan dengan melakukan pertukaran baris pada matriks lengkap SPL. Elemen penumpunya diambil dari $$\max_{k\leq i\leq n} |a_{i,k}|$$Setelah elemen penumpu dipilih, kita harus menempatkannya pada posisi $(k,k)$ dari matriks lengkap SPL.

In [6]:
% Eliminasi Gauss dengan Penumpuan Parsial

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n+1)       % matriks ekspansi Ax=b, yakni [A b]

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma
start_process = true;

for k=1:(n-1)
    % cari baris untuk pivot
    [val, pivot] = max(abs(A(k:n, k)));

    if abs(val) < 10^(-15)
        printf('proses gagal: tidak ada elemen pivot yang tak nol\n')
        start_process = false;
        break
    end
    
    % tukar posisi
    temp            = A(k, :);
    A(k, :)         = A(k-1+pivot, :);
    A(k-1+pivot, :) = temp;
    
    % mulai eliminasi
    for i=(k+1):n
        p = A(i, k)/A(k, k);
        A(i, :) = A(i, :) - p * A(k, :);
    end
end

if start_process
    % mulai penyulihan
    x(n) = A(n, n+1) / A(n, n);
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end
x

A =

    8    3   -8   -7    7    9
    0    6   -3   -7   -5    8
   -6    5    8   -6   -7    7
    7    8   -5    4    2   10
    3    0  -10    5   -5    8

x =

   9.8621  -2.7167   4.1803  -1.3854  -5.4288



### Modifikasi Eliminasi Gauss untuk SPL Tridiagonal

In [7]:
n = 10;
A = randi([-100 100], n, n);
A = triu(triu(A, -1)', -1);
b = randi([-10 10], n, 1);

[A b]

ans =

  -44   61    0    0    0    0    0    0    0    0   -3
   59   96  -45    0    0    0    0    0    0    0    5
    0   57  -35   40    0    0    0    0    0    0    9
    0    0   11   -1   54    0    0    0    0    0    7
    0    0    0   12  -29  -14    0    0    0    0   -2
    0    0    0    0   75   52   -9    0    0    0    2
    0    0    0    0    0  -77  -16   50    0    0    6
    0    0    0    0    0    0   64   -8  -77    0   -2
    0    0    0    0    0    0    0   30   57   95    7
    0    0    0    0    0    0    0    0   65  -66    1



bila SPL tridiagonal seperti matriks A di atas disimpan dalam bentuk matriks lengkap, akan diperlukan banyak memori untuk menyimpan memori yang bernilai nol. Karena itu, matriks A disimpan dalam bentuk tiga vektor

In [8]:
a = zeros(1, n);
d = zeros(1, n);
c = zeros(1, n);

d(n) = A(n, n);
for k = 1:n-1
    a(k+1) = A(k+1, k);
    d(k)   = A(k,   k);
    c(k)   = A(k, k+1);
end

[a' d' c' b]

ans =

    0  -44   61   -3
   59   96  -45    5
   57  -35   40    9
   11   -1   54    7
   12  -29  -14   -2
   75   52   -9    2
  -77  -16   50    6
   64   -8  -77   -2
   30   57   95    7
   65  -66    0    1



In [9]:
% Eliminasi Gauss untuk SPL Tridiagonal

% Masukan
n;               % ukuran matriks
a; d; c;         % vektor dari tridiagonal SPL
v = b;           % untuk pengecekan

% Keluaran
x = zeros(1, n);  % solusi SPL

% Algoritma

% cek penumpu
if min(abs(d)) < 10^(-15)
    printf('proses gagal: penumpu bernilai nol')
else
    % Gauss
    for k=1:n-1
        p = a(k+1)/d(k);
        d(k+1) = d(k+1) - p*c(k);
        b(k+1) = b(k+1) - p*b(k);
        a(k+1) = 0;
    end

    % Penyulihan mundur
    x(n) = b(n)/d(n);
    for k=(n-1):-1:1
        x(k) = (b(k) - c(k)*x(k+1))/d(k);
    end

end

x'

ans =

  -0.046108
  -0.082439
  -0.347433
   0.038471
   0.201115
  -0.240764
   0.062660
  -0.230725
   0.102026
   0.085329



In [10]:
rref([A v])(:,n+1)

ans =

  -0.046108
  -0.082439
  -0.347433
   0.038471
   0.201115
  -0.240764
   0.062660
  -0.230725
   0.102026
   0.085329



## Perhitungan Determinan
Untuk melakukan perhitungan determinan terhadap matriks $A$, kita cukup mengubahnya menjadi matriks segitiga atas $B$. Beberapa hal perlu diperhatikan pada saat melakukan proses OBE, yaitu:
1. Penukaran dua buah baris akan membuat nilai determinan matriks yang baru merupakan negatif dari determinan matriks semula.
2. Bila suatu baris dikali dengan konstanta $k$ maka nilai determinannya menjadi $k$ kali nilai determinan matriks semula.
3. Bila suatu baris ditambah dengan $k$ kali baris yang lain, nilai determinannya tidak berubah.

Selanjutnya, $$\det(B) = \prod_{i=1}^n a_{ii}$$

## Perhitungan Invers Matriks
Invers dari sebuah matriks $A$ dapat dicari dengan mengubah bentuk matriks ekspansi $$[A\,I]$$ menjadi bentuk $$[I\,B]$$Dengan demikian, matriks $B$ adalah invers dari matriks $A$. Proses pengubahan matriks $A$ menjadi $I$ dapat dilakukan lewat metode Gauss-Jordan

In [11]:
% Eliminasi Gauss-Jordan

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n);        % matriks A
M = [A eye(n, n)];                 % matriks ekspansi [A I]

% Keluaran
B = zeros(n, n);                   % invers matriks A

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for i=n:-1:1
    if abs(M(i,i)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

if start_process
    % Gauss
    for k=1:n-1
        for i=(k+1):n
            p = M(i, k)/M(k, k);
            M(i, :) = M(i, :) - p * M(k, :);
        end       
    end
    
    % Jordan
    for k=n:-1:1
        for i=(k-1):-1:1
            p = M(i, k)/M(k, k);
            M(i, :) = M(i, :) - p * M(k, :);
        end
        
        M(k, :) = M(k, :)/ M(k,k);
    end
    
    B = M(:, n+1:2*n)
end

B =

   0.0705199   0.0405897  -0.1038666  -0.0771795  -0.0256177
   0.0345898   0.0548673   0.0436869   0.0174859   0.0324370
  -0.1018666  -0.0192428   0.0482146  -0.0458744   0.0229233
   0.0602631  -0.0312912  -0.0082082  -0.0323746  -0.0533048
   0.0020000  -0.0150970  -0.0159442  -0.0222775   0.0825822



In [12]:
A*B

ans =

   1.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   1.00000  -0.00000  -0.00000   0.00000
   0.00000   0.00000   1.00000   0.00000  -0.00000
   0.00000   0.00000   0.00000   1.00000  -0.00000
  -0.00000   0.00000   0.00000   0.00000   1.00000



## Dekomposisi Matriks
Metode dekomposisi matriks digunakan untuk memfaktorkan suatu matriks atas faktor matriks segitiga atas dan segitiga bawah. Langkah untuk mencari penyelesaian SPL dengan metode dekomposisi adalah sebagai berikut:
$$A\overline{x} = \overline{b} \\
(LU)\overline{x} =\overline{b} \\
L(U\overline{x}) = \overline{b} \\
$$

Misalkan $\overline{y} = U\overline{x}$. Kita selesaikan SPL segitiga bawah $L\overline{y} = \overline{b}$ dengan penyulihan maju. Setelah vektor $\overline{y}$ diperoleh selanjutnya vektor $\overline{x}$ dapat dicari dari persamaan $U\overline{x} = \overline{y}$ dengan memakai penyulihan mundur. 

### Dekomposisi Doolitle
Pada dekomposisi Doolitle, elemen diagonal dari matriks segitiga bawah dipilih bernilai 1. Langkah-langkah Perhitungan Dekomposisi Doolitle
* Kalikan baris satu dari matriks $L$ dengan matriks $U$, diperoleh nilai-nilai $u_{11}, u_{12}, u_{13}, \dots, u_{1n}$.
* Kalikan matriks $L$ dengan kolom satu dari matriks $U$, diperoleh nilai-nilai $l_{21}, l_{31}, l_{41}, \dots, l_{n1}$.
* Kalikan baris dua dari matriks $L$ dengan matriks $U$, diperoleh nilai-nilai $u_{22}, u_{23}, u_{24}, \dots, u_{2n}$.
* Kalikan matriks $L$ dengan kolom dua dari matriks $U$, diperoleh nilai-nilai $l_{32}, l_{42}, l_{52}, \dots, l_{n2}$.
* Proses yang serupa dilakukan sampai elemen-elemen matriks $L$ dan $U$ semuanya terhitung.

In [2]:
A = randi([-10, 10], 6, 6)
L = eye(6, 6);
U = zeros(6, 6);

for i=1:6
    for k=i:6
        U(i, k) = A(i, k) - dot(L(i, 1:i), U(1:i, k));
    end
    
    for k=(i+1):6
        L(k, i) = (A(k, i) - dot(L(k, 1:i), U(1:i, i)))/ U(i, i);
    end
end

A =

   -2   -8   -3   -3   -1    6
  -10    9   -8    2    7   -6
   -4    0    0   -8   -9   -7
   -1    7    7    0    4   -1
   -3   -9    2   -7    0  -10
    8    5   -3   -5   -3    8



In [3]:
L*U - A

ans =

   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00
   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00
   0.0000e+00  -1.7764e-15   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00
   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00
   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00  -1.7764e-15
   0.0000e+00   3.5527e-15   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00



## Metode Iterasi Untuk Menyelesaikan SPL

### Metode Jacobi
Matriks koefisien $A$ pada persamaan $$Ax = b$$ dapat didekomposisi menjadi matriks diagonal $D$ dan sisa $R$. Dengan kata lain,

$$A = D+R = 
\begin{bmatrix}
a_{11} & 0 & \cdots & 0 \\
0 & a_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn} 
\end{bmatrix} + 
\begin{bmatrix}
0 & a_{12} & \cdots & a_{1n} \\
a_{21} & 0 & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & 0
\end{bmatrix}.
$$

Sehingga
$$
\begin{align}
Ax &= b \\
(D+R)x &= b\\
Dx &= b - Rx \\
x &= D^{-1} (b - Rx) \\
\end{align}
$$

Sehingga solusi dari persamaan dapat ditentukan secara iteratif dengan
$$ x^{(k+1)} = D^{-1} (b - R x^{(k)}) $$

dimana $x^{(k)}$ adalah aproksimasi ke-*k* dari $x$. Rumus iterasi Metode Jacobi versi elemen matriks adalah
$$x^{(k+1)}_i := \frac{1}{a_{ii}}\Big(b_i - \sum_{j=1, j\neq i}^n a_{ij}x^{(k)}_j \Big)$$

dengan kriteria penghentian iterasi yaitu:
$$\max_{1\leq i\leq n} \frac{|a^{k+1}_i − a^k_i|}{|a^{k+1}_i|} < \epsilon $$

_note from **keka.vigi**_ :

* metode iterasi seperti ini rasanya enak dipakai jika tebakan awal $x^{(0)}$ berada dekat dengan solusi eksaknya. Cukup efisien kalau matriks $A$ dimensinya besar, *sparse*, dan *diagonally dominated*. Tapi enak dipakai belum tentu bisa *casually assumed* cara ini bakal konvergen. Seperti, bahkan untuk $A$ berupa matriks tridiagonal yang dibangkitkan secara acak, iterasi metode ini meledak-ledak macam petasan tahun baru.
* kriteria penghentian iterasinya aneh euy, bukannya lebih wajar jika memakai galat hasil perbandingan iterasi sebelumnya? saya gatau karena sering main lompat tali kelas matnum :(. Bagaimana kalau sanity check dari $D^{-1}R$ terlebih dulu? kalau absolut dari limit matriks ini lebih dari 1, sudah pasti tidak konvergen ngga sih?

In [4]:
% Algoritma

% Masukan
n = 4;                   % ukuran matriks
A = [10 -1  2  0;
     -1 11 -1  3;
      2 -1 10 -1;
      0  3 -1  8];
b = [6 25 -11 15]';
eps = 10^-8;

% Keluaran
x = zeros(n, 1);

% Algoritma
x_old = zeros(n, 1);
D = diag(diag(A));
R = A-D;

for iteration = 1:1000
    x = D\(b - R*x);
    if norm(x_old - x) < eps
        break
    else
        x_old = x;
    end
end

% Keluaran
x

x =

   1.00000
   2.00000
  -1.00000
   1.00000



In [5]:
A*x - b

ans =

   1.1958e-08
  -2.2090e-08
   1.5531e-08
  -1.7699e-08



### Metode Gauss Seidel
Secara umum, rumus iterasi metode Gauss Seidel adalah
$$x^{k+1}_i := \frac{1}{a_{ii}} \Big(b_i - \sum^{i−1}_{j=1} a_{ij}x^{k+1}_j + \sum^n_{j=i+1} a_{ij}x^k_j \Big) $$

dengan kriteria penghentian iterasi:
$$ \max_{1\leq i \leq n} \frac{|a^{k+1}_i − a^k_i|}{|a^{k+1}_i|} < \epsilon $$

_note dari **keka.vigi**_ :
* bagaimana kalau $x_{n+1} = L_*^{-1} (b -U x_n)$ ? sekali lagi, beda sama diktat. Ini bahkan beda sama [Wikipedia](https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method)


In [2]:
% Algoritma

% Masukan
n = 4;                   % ukuran matriks
A = [10 -1  2  0;
     -1 11 -1  3;
      2 -1 10 -1;
      0  3 -1  8];
b = [6 25 -11 15]';
eps = 10^-8;

% Keluaran
x = zeros(n, 1);

% Algoritma
x_old = zeros(n, 1);
L = tril(A);
U = triu(A, 1);

for iteration = 1:1000
    x = L\(b - U*x);
    if norm(x_old - x) < eps
        break
    else
        x_old = x;
    end
end

% Keluaran
x

x =

   1.00000
   2.00000
  -1.00000
   1.00000



In [3]:
A*x-b

ans =

   5.5764e-11
  -1.3883e-09
   2.9453e-10
   0.0000e+00

